# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainwindow.ui',
# licensing of './ui/mainwindow.ui' applies.
#
# Created: Mon Jun  3 10:43:00 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.le_path = QtWidgets.QLineEdit(self.groupBox)
        self.le_path.setObjectName("le_path")
        self.horizontalLayout_2.addWidget(self.le_path)
        self.pb_browser = QtWidgets.QPushButton(self.groupBox)
        self.pb_browser.setObjectName("pb_browser")
        self.horizontalLayout_2.addWidget(self.pb_browser)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.le_threadnum = QtWidgets.QLineEdit(self.groupBox)
        self.le_threadnum.setObjectName("le_threadnum")
        self.horizontalLayout_3.addWidget(self.le_threadnum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pb_addTask = QtWidgets.QPushButton(self.frame_3)
        self.pb_addTask.setObjectName("pb_addTask")
        self.verticalLayout_4.addWidget(self.pb_addTask)
        self.pb_clear = QtWidgets.QPushButton(self.frame_3)
        self.pb_clear.setObjectName("pb_clear")
        self.verticalLayout_4.addWidget(self.pb_clear)
        self.pb_start = QtWidgets.QPushButton(self.frame_3)
        self.pb_start.setObjectName("pb_start")
        self.verticalLayout_4.addWidget(self.pb_start)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 834, 335))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tb_task = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tb_task.setObjectName("tb_task")
        self.tb_task.setColumnCount(5)
        self.tb_task.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_task.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_task.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_task.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_task.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_task.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.tb_task)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "地图下载器", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "选项", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "保存路径", None, -1))
        self.pb_browser.setText(QtWidgets.QApplication.translate("MainWindow", ">>>", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "最大线程数", None, -1))
        self.le_threadnum.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.pb_addTask.setText(QtWidgets.QApplication.translate("MainWindow", "增加任务", None, -1))
        self.pb_clear.setText(QtWidgets.QApplication.translate("MainWindow", "清除任务", None, -1))
        self.pb_start.setText(QtWidgets.QApplication.translate("MainWindow", "开始下载", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "任务列表", None, -1))
        self.tb_task.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "地图", None, -1))
        self.tb_task.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "级别", None, -1))
        self.tb_task.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "范围", None, -1))
        self.tb_task.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "状态", None, -1))
        self.tb_task.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "进度", None, -1))

